name: money_man
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rounded_loading_button: ^1.0.0
  slide_button: ^0.2.8
  progress_state_button: ^1.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  flutter_swiper: ^1.1.6
  passwordfield: ^0.0.82
  flutter_spinkit: "^4.1.2"
  email_validator: '^1.0.6'
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  provider: ^4.3.3
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  sticky_headers: "^0.1.8"
  # flutter_facebook_auth: "^1.0.1"
  # flutter_facebook_auth: ^3.5.0
  flutter_facebook_login: ^3.0.0
  currency_picker: ^2.0.4
  page_transition: ^1.1.7+6
  modal_bottom_sheet: ^2.0.0
  math_expressions: ^2.0.0
  money_formatter: ^0.0.3
  fl_chart: ^0.36.1
  charts_flutter: ^0.10.0
  pie_chart: ^5.0.0
  flutter_svg: ^0.22.0
  random_color: ^1.0.5
  flutter_datetime_picker: ^1.5.1
  rflutter_alert: ^1.0.2
  share: ^2.0.1
  path_provider: ^2.0.1
  image_gallery_saver: ^1.6.9
  get_it: ^7.1.3
  url_launcher: ^6.0.6
  date_util: ^0.1.4
  fluttercontactpicker: ^4.4.0
  mailer: ^5.0.0
  connectivity_plus: ^1.0.4
  permission_handler: ^8.1.2

dev_dependencies:
 # flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter

#flutter_icons:
#  android: true
#  image_path: "assets/images/app_icon2.png"
 # adaptive_icon_background: "#ffffff"
  #adaptive_icon_foreground: "assets/images/app_icon2.png"

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/carousel/
     - assets/images/avatars/
     - assets/icons/
     - assets/images/account_screen/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
